FROM node:13-alpine AS ui-build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY . ./

#replace config
COPY ./config.docker.json ./config-dev.json
RUN npm run build

CMD ["node", "router.js"]