const aliasMap = {username: "Username",
projectid: "Project ID",
projectname: "Project Name",
typeofrecord: "Type of Record",
floodhzdstd: "Flood Hazard Standard",
officialwcname: "Official Watercourse Name",
watershed: "Watershed",
caundertaking: "Undertaking: CA",
munundertaking: "Undertaking: Municipality",
privundertaking: "Undertaking: Private",
fedundertaking : "Undertaking: Federal",
otherundertaking: "Undertaking: Other",
reportyear: "Report Year ",
datasetstatus: "Floodline Dataset Status ",
lastprojupdate: "Project Last Updated",
partupdate: "Partially Updated ",
isrequpdate: "Update Currently Required ",
updatepurp: "Required Update Purpose ",
projectcat: "Project Category ",
drainagearea: "Drainage Area (sq km)",
summreportavail: "Summary Report Available",
updatesinceorig: "Update Since Original",
localwcname: "Local Watercourse Name ",
fdrpproject: "FDRP Project",
wclength: "Watercourse Length (km)",
widestcswidth: "Widest Cross Section Width (m)",
maxfloodplain: "Maximum Floodplain Extent (m)",
percenthighhzd: "Percent High Hazard ",
percentmedhzd: "Percent Medium Hazard",
percentlowhzd: "Percent Low Hazard ",
urbanfloodconcern: "Urban Flood Concerns",
plan2zone: "Planning Designation 2-Zone",
planspa: "Planning Designation SPA",
majorevent: "Major Event Since 1996",
0: "Structures Within the Floodplain",
buildingsatrisk: "Estimate Buildings at Risk",
otheratrisk: "Other Event Buildings at Risk",
extent: "Extent",
coordinatesysproj: "Coordinate System/Projection",
generalprojcomments: "General Comments Project",
imgprojid: "(Imagery) Project ID",
acquisitionyear: "(Imagery) Year of Acquisition",
datadescrip: "(Imagery) Data Description ",
acquisitionseason: "(Imagery) Season of Acquisition",
imghref: "(Imagery) Horizontal Reference",
imgvref: "(Imagery) Vertical Reference",
imghozacc: "(Imagery) Stated Horizontal Accuracy (m)",
imgderivmethod: "(Imagery) Accuracy Derivation Method",
spatialreshoz: "(Imagery) Horizontal Spatial Resolution",
spatialresvert: "(Imagery) Vertical Spatial Resolution",
imgpeerreview: "(Imagery) Peer Review",
imggeneralcomments: "(Imagery) General Comments",
elevprojid: "(Elevation) Project ID",
digitaldata: "(Elevation) Digital Data",
dataformat: "(Elevation) Data Format",
primdatasource: "(Elevation) Primary Data Source",
elevdataowner: "(Elevation) Data Owner",
elevhref: "(Elevation) Horizontal Reference",
elevvref: "(Elevation) Vertical Reference",
elevhozacc: "(Elevation) Stated Horizontal Accuracy",
elevvertacc: "(Elevation) Stated Vertical Accuracy",
elevderivmethod: "(Elevation) Accuracy Derivation Method",
elevspatialreshoz: "(Elevation) Horizontal Spatial Resolution",
elevspatialresvert: "(Elevation) Vertical Spatial Resolution",
secdatasource: "(Elevation) Secondary Data Source",
elevpeerreview: "(Elevation) Peer Review",
elevgeneralcomments: "(Elevation) General Comments",
hydroprojid: "(Hydrology) Project ID",
hydromethod: "(Hydrology) Method/Model",
hydroyear: "(Hydrology) Year of Hydrology",
datasetyrs: "(Hydrology) Years in Dataset",
eventsmodelled: "(Hydrology) Events Modeled",
ismodelcalib: "(Hydrology) Calibrated Model",
calibquality: "(Hydrology) Hydrology Quality of Calibration",
inputparamquality: "Hydrology Quality of Input Parameters",
inputcomments: "(Hydrology) Quality of Input Comments",
hydromodelyear: "(Hydrology) Model Year",
smincorporated: "(Hydrology) Snowmelt Incorporated",
volreduction: "(Hydrology) Peak or Volume Reduction",
catdiscretized: "(Hydrology) Catchments Discretized",
hydrosupportingdoc: "(Hydrology) Adequate Supporting Documentation",
ccconsidered: "(Hydrology) Climate Change Considered",
hydropeerreview: "(Hydrology) Peer Review",
hydrogeneralcomments: "(Hydrology) General Comments",
hydraprojid: "(Hydraulics) Project ID",
hydrayear: "(Hydraulics) Year of Model Run",
hydramethod: "(Hydraulics) Hydraulic Model",
flowcond: "(Hydraulics) Flow Condition",
hydracalib: "(Hydraulics) Calibration Process",
hydrainputcomments: "(Hydraulics) Quality of Input Comments",
floodlineestimated: "(Hydraulics) Estimated Floodline",
hydrasupportingdoc: "(Hydraulics) Adequate Supporting Documentation",
elevsource: "(Hydraulics) Elevation Source",
onedeffective: "1D Modelling Appropriate",
hydrapeerreview: "(Hydraulics) Peer Review",
hydrageneralcomments: "(Hydraulics) General Comments",
boundingbox: "Bounding Box",
privateundertakingname: "Private Undertaking Name",
otherundertakingname: "Other Undertaking Name",
submissionid: "Submission ID",
climatechangecomments: "(Hydrology) Climate Change Comments",
otherfloodhzd: "Other Flood Hazard Event"};

export default aliasMap;