const aliasMap = {username: "Username",
projectid: "Project ID",
projectname: "Project Name",
typeofrecord: "Type of Record",
floodhzdstd: "Flood Hazard Standard",
officialwcname: "Official Watercourse Name",
watershed: "Watershed",
caundertaking: "Undertaking: CA",
munundertaking: "Undertaking: Municipality",
privundertaking: "Undertaking: Private",
fedundertaking : "Undertaking: Federal",
otherundertaking: "Undertaking: Other",
reportyear: "Report Year ",
datasetstatus: "Floodline Dataset Status ",
lastprojupdate: "Project Last Updated",
partupdate: "Partially Updated ",
isrequpdate: "Update Currently Required ",
updatepurp: "Required Update Purpose ",
projectcat: "Project Category ",
drainagearea: "Drainage Area (sq km)",
summreportavail: "Summary Report Available",
updatesinceorig: "Update Since Original",
localwcname: "Local Watercourse Name ",
fdrpproject: "FDRP Project",
wclength: "Watercourse Length (km)",
widestcswidth: "Widest Cross Section Width (m)",
maxfloodplain: "Maximum Floodplain Extent (m)",
percenthighhzd: "Percent High Hazard ",
percentmedhzd: "Percent Medium Hazard",
percentlowhzd: "Percent Low Hazard ",
urbanfloodconcern: "Urban Flood Concerns",
plan2zone: "Planning Designation 2-Zone",
planspa: "Planning Designation SPA",
majorevent: "Major Event Since 1996",
0: "Structures Within the Floodplain",
buildingsatrisk: "Estimate Buildings at Risk",
otheratrisk: "Other Event Buildings at Risk",
extent: "Extent",
coordinatesysproj: "Project/Datum… 1 or fields..",
generalprojcomments: "General Comments Project",
imgprojid: "(Imagery) Project ID",
acquisitionyear: "Year of Acquisition",
datadescrip: "Data Description ",
acquisitionseason: "Season of Acquisition",
imghref: "(Imagery) Horizontal Reference",
imgvref: "(Imagery) Vertical Reference",
imghozacc: "(Imagery) Stated Horizontal Accuracy (m)",
imgderivmethod: "(Imagery)Accuracy Derivation Method",
imgspatialres: "(Imagery) Spatial Resolution",
imgpeerreview: "(Imagery) Peer Review",
imggeneralcomm: "General Comments Imagery",
elevprojectid: "(Elevation) Project ID",
digitaldata: "Digital Data",
dataformat: "Data Format",
primarydatasource: "Primary Data Source",
elevdataowner: "Elevation Data Owner",
elevhref: "(Elevation) Horizontal Reference",
elevvref: "(Elevation) Vertical Reference",
elevhozacc: "(Elevation) Stated Horizontal Accuracy",
elevvertacc: "(Elevation) Stated Vertical Accuracy",
elevderivmethod: "(Elevation) Accuracy Derivation Method",
elevspatialres: "(Elevation) Spatial Resolution",
secdatasource: "Secondary Data Source",
elevpeerreview: "(Elevation) Peer Review",
elevgeneralcomm: "General Comments Elevation ",
hydroprojid: "(Hydrology) Project ID",
hydromethod: "Hydrology Method/Model",
hydroyear: "Year of Hydrology",
datasetyrs: "Years in Dataset",
eventsmodeled: "Events Modeled",
ismodelcalib: "Calibrated Model",
calibquality: "Hydrology Quality of Calibration ",
inputparamquality: "Hydrology Quality of Input Parameters",
inputcomments: "Hydrology Quality of Input Comments",
hydromodelyear: "Planning Horizon",
smincorporated: "Snowmelt Incorporated",
volreduction: "Peak or Volume Reduction",
catdiscretized: "Catchments Discretized",
hydrosupportingdoc: "(Hydrology) Adequate Supporting Documentation",
ccconsidered: "Climate Change Considered",
hydropeerreview: "(Hydrology) Peer Review",
hydrogeneralcomments: "General Comments Hydrology",
hydraprojectid: "(Hydraulics) Project ID",
hydramodelyear: "Year of Model Run ",
hydramodel: "Hydraulic Model ",
flowcond: "Flow Condition",
hydracalib: "Calibration Process",
hydracalibquality: "Hydraulics Quality of Calibration",
hydraparamquality: "Hydraulics Quality of Input Parameters",
hydraqualitycomments: "Hydraulics Quality of Input Comments",
floodlineestimated: "Estimated Floodline",
hydrasupportingdoc: "(Hydraulics) Adequate Supporting Documentation",
elevsource: "Elevation Source",
onedeffective: "1D Modelling Appropriate",
hydrapeerreview: "(Hydraulics) Peer Review",
hydrageneralcomments: "General Comments Hydraulics"};

export default aliasMap;